package cdc

// ChunkReader can be used to read the contents of a file as a series of
// chunks that were generated by a Content-Defined Chunking function.
type ChunkReader interface {
	ReadNextChunk() ([]byte, error)
}

// ContentDefinedChunker represents a Content-Defined Chunking function
// can be used to decompose a large file into smaller chunks. Cutting
// points are determined by inspecting the binary content of the file.
type ContentDefinedChunker interface {
	// Read the contents of a file, returning its contents as a
	// sequence of chunks.
	NewChunkReader(peeker Peeker) ChunkReader
}
